### ISSUE TITLE
ErrorException [ Fatal Error ]: Interface 'Twig_LoaderInterface' not found

### ISSUE THREAD

**Issue by tomeroto** [errotan/koseven-twig#2]
Hi there,

I have a problem to use the twig wrapper for koseven. After following the instalation documentation, and complete it, I see an error message below:

`ErrorException [ Fatal Error ]: Interface 'Twig_LoaderInterface' not found`

Just info, I use MAMP for Mac that have bundle PHP7, MYSQL, and etc.

**Comment by errotan** [comment]
Made a quick test with a fresh koseven install and can't reproduce your error.

Environment: Win 10, php 7.0 built in server.

**Comment by errotan** [comment]
I can reproduce it now. You are not loading the composer autoloader.

**Comment by errotan** [comment]
Closing this as there is no sign of problem in the code as far as I know.

**Comment by tomeroto** [comment]
please see my pull request :)
